guests_list = ["Dan","Keil","Andrei","Kloe","Adolfo","Franco"]

print(guests_list[0] + ", please come for the dinner.")
print()
print(guests_list[1] + ", please come for the dinner.")
print()
print(guests_list[2] + ", please come for the dinner.")
print()
print(guests_list[3] + ", please come for the dinner.")
print()
print(guests_list[4] + ", please come for the dinner. ")
print()
print("Sorry, " + guests_list[3] + " can't come to the dinner tonight. Let's invite Kaela, Harold, and Keith instead.")
print()
del(guests_list[3])
guests_list.insert(5,"Kaela")
guests_list.insert(6,"Harold")
guests_list.insert(7, 'Keith')
print(guests_list)
print()
print("Okay, changing guests' list.")
print()
print(guests_list[0] + ", please come for the dinner.")
print()
print(guests_list[1] + ", please come for the dinner.")
print()
print(guests_list[2] + ", please come for the dinner.")
print()
print(guests_list[3] + ", please come for the dinner.")
print()
print(guests_list[4] + ", please come for the dinner.")
print()
print(guests_list[5] + ", please come for the dinner.")
print()
print(guests_list [6] + ", please come for the dinner.")
print()
print(guests_list [7] + ", please come for the dinner.")
print()
print("I hope that everyone is doing well, but unfortunately, only two guests will be recognized.")
print()
print(guests_list[0] + ", please come for the dinner.")
print()
print(guests_list[1] + ", please come for the dinner.")
print()
print("Sorry " + guests_list[2] + ", we can't accomodate you for the dinner.")
print()
print("Sorry " + guests_list[3] + ", we can't accomodate you for the dinner.")
print()
print("Sorry " + guests_list[4] + ", we can't accomodate you for the dinner.")
print()
print("Sorry " + guests_list[5] + ", we can't accomodate you for the dinner.")
print()
print("Sorry " + guests_list[6] + ", we can't accomodate you for the dinner.")
print()
print("Sorry " + guests_list[7] + ", we can't accomodate you for the dinner.")
print()
guests_list.pop()
guests_list.pop()
guests_list.pop()
guests_list.pop()
guests_list.pop()
guests_list.pop()
print("Dan and Keil are still invited since they are the first and second on the guests' list.")
print()
print("Hi " + guests_list[0] +", you are one of the recognized guests at the dinner, please come.")
print()
print("Hi " + guests_list[1] +", you are one of the recognized guests at the dinner, please come.")
print()
del(guests_list[0])
del(guests_list[0])
print(guests_list)