guests_list = ["Dan","Keil","Andrei","Adolfo","Franco"]

print(guests_list[0] + ", please come to dinner.")
print()
print(guests_list[1] + ", please come to dinner.")
print()
print(guests_list[2] + ", please come to dinner.")
print()
print(guests_list[3] + ", please come to dinner.")
print()
print("Sorry, " + guests_list[3] + " can't come to dinner. Let's invite Kaela instead.")
print()
del(guests_list[3])
guests_list.insert(3,"Kaela")
print("Okay, changing guests' list.")
print(guests_list)
print()
print(guests_list[0] + ", please come to dinner.")
print()
print(guests_list[1] + ", please come to dinner.")
print()
print(guests_list[2] + ", please come to dinner.")
print()
print(guests_list[3] + ", please come to dinner.")