Mountains = ["Mayon Volcano", "Mount Everest","Mount Fuji","Himalayas Mountains","Mount Makiling"]
print()
print("This is the raw order: ")
print(Mountains)
print()
print("Alphabetical order of the mountains: ")
print(sorted(Mountains))
print()
print("This is the raw order: ")
print(Mountains)
print()
print("Reversed Alphabetical order of the mountains: ")
print(sorted(Mountains, reverse=True))
print()
print("This is the raw order: ")
print(Mountains)
print()
print("Reversed raw order: ")
Mountains.reverse()
print(Mountains)
print()
print("This is the raw order: ")
Mountains.reverse()
print(Mountains)
print()
print("Second round of alphabetical order: ")
Mountains.sort()
print(Mountains)
print()
print("Second round of reverse alphabetical order: ")
Mountains.sort(reverse = True)
print(Mountains)
print()